name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SoftEtherVPN/SoftEtherVPN
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake gcc g++ ninja-build libncurses5-dev libreadline-dev libsodium-dev libssl-dev make zlib1g-dev liblz4-dev libnl-genl-3-dev

      - name: Build
        run: |
          echo "commit=$(git show --format='%h' --no-patch)" >> $GITHUB_ENV
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          cmake --build .
          cpack -C Release -G DEB
          sudo chown -R runner:runner .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SoftEtherVPN@${{ env.commit }}
          path: build/_CPack_Packages/Linux/DEB/*.deb
