name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SoftEtherVPN/SoftEtherVPN
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake gcc g++ ninja-build libncurses5-dev libreadline-dev libsodium-dev libssl-dev make zlib1g-dev liblz4-dev libnl-genl-3-dev

      - name: Build
        run: |
          echo "commit=$(git show --format='%h' --no-patch)" >> $GITHUB_ENV
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          cmake --build .
          cpack -C Release -G DEB

      - name: Set env
        run: |
          declare -A ARCH_MAP=([ubuntu-24.04]="amd64" [ubuntu-24.04-arm]="arm64")
          echo "arch=${ARCH_MAP[${{ matrix.os }}]}" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SoftEtherVPN-${{ env.arch }}@${{ env.commit }}
          path: build/*.deb
